
import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class LOGIN_window extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_window
     */
    public LOGIN_window() {
        initComponents();
       
        //center the form
        this.setLocationRelativeTo(null);
        
        //display image in the jlabel
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image.jpg")));
        Username_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png")));
        Password_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pswrd.png")));
        
        //add a bottom border to the jlabel title
        Border title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.RED);
        jLabel_Title.setBorder(title_border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Image = new javax.swing.JLabel();
        jLabel_Title = new javax.swing.JLabel();
        Username_Icon = new javax.swing.JLabel();
        Password_Icon = new javax.swing.JLabel();
        jTextField1_Username = new javax.swing.JTextField();
        jPasswordField1_Password = new javax.swing.JPasswordField();
        jButton_LogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel_Image.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Image.setOpaque(true);

        jLabel_Title.setFont(new java.awt.Font("Bookman Old Style", 1, 50)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_Title.setText("LOGIN");

        Username_Icon.setBackground(new java.awt.Color(153, 153, 255));
        Username_Icon.setOpaque(true);

        Password_Icon.setBackground(new java.awt.Color(153, 153, 255));
        Password_Icon.setOpaque(true);

        jTextField1_Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1_Username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1_Username.setText("Username");
        jTextField1_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_UsernameFocusLost(evt);
            }
        });

        jPasswordField1_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1_Password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1_Password.setText("password");
        jPasswordField1_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_PasswordActionPerformed(evt);
            }
        });
        jPasswordField1_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1_PasswordFocusLost(evt);
            }
        });

        jButton_LogIn.setBackground(new java.awt.Color(102, 102, 255));
        jButton_LogIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_LogIn.setForeground(new java.awt.Color(240, 240, 240));
        jButton_LogIn.setText("Log In");
        jButton_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_Title)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Username_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Password_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPasswordField1_Password)))
                    .addComponent(jButton_LogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UsernameFocusGained
        // remove the text from the text field on focus gained
        //if the text field text="username"
        
        if(jTextField1_Username.getText().trim().equals("Username")){
            jTextField1_Username.setText("");
            //change the text field color to black
            jTextField1_Username.setForeground(Color.BLACK);
            
        }
        
        
        
    }//GEN-LAST:event_jTextField1_UsernameFocusGained

    private void jTextField1_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UsernameFocusLost
        // TODO add your handling code here:
        
         if(jTextField1_Username.getText().trim().equals("") || jTextField1_Username.getText().trim().toLowerCase().equals("username"))
         {
             jTextField1_Username.setText("Username");
             jTextField1_Username.setForeground(new Color(153,153,153));
            
         }
        
    }//GEN-LAST:event_jTextField1_UsernameFocusLost

    private void jPasswordField1_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_PasswordFocusGained
        String password = String.valueOf(jPasswordField1_Password.getPassword());
        if(password.trim().toLowerCase().toLowerCase().equals("password"))
        {
            jPasswordField1_Password.setText("");
            jPasswordField1_Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField1_PasswordFocusGained

    private void jPasswordField1_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_PasswordFocusLost
        String password = String.valueOf(jPasswordField1_Password.getPassword());
         if(password.trim().equals("") || password.trim().equals("password"))
         {
            jPasswordField1_Password.setText("password");
            jPasswordField1_Password.setForeground(new Color(153,153,153));
            
         }
        

    }//GEN-LAST:event_jPasswordField1_PasswordFocusLost

    private void jButton_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogInActionPerformed
       
        String username = jTextField1_Username.getText();
        String password = String.valueOf(jPasswordField1_Password.getPassword());
        
        PreparedStatement ps;
        ResultSet rs;        
        
        String selectQuery = "SELECT * FROM `Users` WHERE `username`=? AND `password`=?";
        
        if (username.trim().toLowerCase().equals("username") ||
                password.trim().toLowerCase().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Enter your username and password","Empty field",2);
        }
        else
        {
            try {
                ps = THE_CONNECTION.getTheConnection().prepareStatement(selectQuery);
                ps.setString(1, username);
                ps.setString(2, password);
           
                rs = ps.executeQuery();
                
                if(rs.next())
                {
                    MAIN_APP_WINDOW mainform = new MAIN_APP_WINDOW();
                    mainform.setVisible(true);
                    
                    mainform.pack();
                    mainform.setExtendedState(Frame.MAXIMIZED_BOTH);

                    this.dispose();
                }
                else
                {
                      JOptionPane.showMessageDialog(null, "Invalid username or password","wrong data",2);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(LOGIN_window.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           
           
        }
        
        
    }//GEN-LAST:event_jButton_LogInActionPerformed

    private void jPasswordField1_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password_Icon;
    private javax.swing.JLabel Username_Icon;
    private javax.swing.JButton jButton_LogIn;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPasswordField jPasswordField1_Password;
    private javax.swing.JTextField jTextField1_Username;
    // End of variables declaration//GEN-END:variables
}
