
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.border.Border;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class MAIN_APP_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_APP_WINDOW
     */
    public MAIN_APP_WINDOW() {
        initComponents();
        
        jLabel_APP_ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download.png")));
        
        Border logo_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE);
        jLabel_APP_ICON.setBorder(logo_border);
        
        Border AppName = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.WHITE);
        jLabel_AppName.setBorder(AppName);
        
        Border menuItems = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.yellow);
        Property.setBorder(menuItems);
        PropertyType.setBorder(menuItems);
        PropertyImages.setBorder(menuItems);
        Owner.setBorder(menuItems);
        Client.setBorder(menuItems);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_APP_ICON = new javax.swing.JLabel();
        jLabel_AppName = new javax.swing.JLabel();
        Property = new javax.swing.JLabel();
        PropertyImages = new javax.swing.JLabel();
        Owner = new javax.swing.JLabel();
        Client = new javax.swing.JLabel();
        PropertyType = new javax.swing.JLabel();
        Sale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel_APP_ICON.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_APP_ICON.setOpaque(true);

        jLabel_AppName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_AppName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AppName.setText("  MyAPP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_APP_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AppName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_AppName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_APP_ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Property.setBackground(new java.awt.Color(102, 102, 102));
        Property.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Property.setForeground(new java.awt.Color(255, 255, 255));
        Property.setText(" Property");
        Property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Property.setOpaque(true);
        Property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropertyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropertyMouseExited(evt);
            }
        });

        PropertyImages.setBackground(new java.awt.Color(102, 102, 102));
        PropertyImages.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PropertyImages.setForeground(new java.awt.Color(255, 255, 255));
        PropertyImages.setText(" Property-Images");
        PropertyImages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PropertyImages.setOpaque(true);
        PropertyImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropertyImagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropertyImagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropertyImagesMouseExited(evt);
            }
        });

        Owner.setBackground(new java.awt.Color(102, 102, 102));
        Owner.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Owner.setForeground(new java.awt.Color(255, 255, 255));
        Owner.setText(" Owner");
        Owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Owner.setOpaque(true);
        Owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OwnerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OwnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OwnerMouseExited(evt);
            }
        });

        Client.setBackground(new java.awt.Color(102, 102, 102));
        Client.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Client.setForeground(new java.awt.Color(255, 255, 255));
        Client.setText(" Client");
        Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Client.setOpaque(true);
        Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientMouseExited(evt);
            }
        });

        PropertyType.setBackground(new java.awt.Color(102, 102, 102));
        PropertyType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        PropertyType.setForeground(new java.awt.Color(255, 255, 255));
        PropertyType.setText(" Property-Type");
        PropertyType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PropertyType.setOpaque(true);
        PropertyType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PropertyTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropertyTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropertyTypeMouseExited(evt);
            }
        });

        Sale.setBackground(new java.awt.Color(102, 102, 102));
        Sale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Sale.setForeground(new java.awt.Color(255, 255, 255));
        Sale.setText(" Sale");
        Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sale.setOpaque(true);
        Sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Client, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Owner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PropertyImages, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PropertyType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Property, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PropertyImages, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Owner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Client, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sale, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 704, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PropertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyMouseEntered
       Property.setBackground(Color.white);
       Property.setForeground(new Color(102,102,102));
       
    }//GEN-LAST:event_PropertyMouseEntered

    private void PropertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyMouseExited
       Property.setBackground(new Color(102,102,102));
       Property.setForeground(Color.white);
    }//GEN-LAST:event_PropertyMouseExited

    private void PropertyTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyTypeMouseEntered
       PropertyType.setBackground(Color.white);
       PropertyType.setForeground(new Color(102,102,102));
           }//GEN-LAST:event_PropertyTypeMouseEntered

    private void PropertyTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyTypeMouseExited
        PropertyType.setBackground(new Color(102,102,102));
       PropertyType.setForeground(Color.white);
    }//GEN-LAST:event_PropertyTypeMouseExited

    private void PropertyImagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyImagesMouseEntered
        PropertyImages.setBackground(Color.white);
        PropertyImages.setForeground(new Color(102,102,102));
       
    }//GEN-LAST:event_PropertyImagesMouseEntered

    private void PropertyImagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyImagesMouseExited
       PropertyImages.setBackground(new Color(102,102,102));
       PropertyImages.setForeground(Color.white);
    }//GEN-LAST:event_PropertyImagesMouseExited

    private void OwnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerMouseEntered
       Owner.setBackground(Color.white);
       Owner.setForeground(new Color(102,102,102));
       
    }//GEN-LAST:event_OwnerMouseEntered

    private void OwnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerMouseExited
       Owner.setBackground(new Color(102,102,102));
       Owner.setForeground(Color.white);
    }//GEN-LAST:event_OwnerMouseExited

    private void ClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseEntered
       Client.setBackground(Color.white);
       Client.setForeground(new Color(102,102,102));
       
    }//GEN-LAST:event_ClientMouseEntered

    private void ClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseExited
       Client.setBackground(new Color(102,102,102));
       Client.setForeground(Color.white);
    }//GEN-LAST:event_ClientMouseExited

    private void PropertyTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyTypeMouseClicked
        
        PROPERTY_TYPE_WINDOW typeform = new PROPERTY_TYPE_WINDOW();
        typeform.setVisible(true);
        typeform.pack();
        typeform.setLocationRelativeTo(null);
        typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_PropertyTypeMouseClicked

    private void OwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OwnerMouseClicked

        OWNER_WINDOW ownerform = new OWNER_WINDOW();
        ownerform.setVisible(true);
        ownerform.pack();
        ownerform.setLocationRelativeTo(null);
        ownerform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
    }//GEN-LAST:event_OwnerMouseClicked

    private void ClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientMouseClicked
        CLIENT_WINDOW clientform = new CLIENT_WINDOW();
        clientform.setVisible(true);
        clientform.pack();
        clientform.setLocationRelativeTo(null);
        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
        
        
    }//GEN-LAST:event_ClientMouseClicked

    private void PropertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyMouseClicked
        
        PROPERTY_WINDOW propertyform = new PROPERTY_WINDOW();
        propertyform.setVisible(true);
        propertyform.pack();
        propertyform.setLocationRelativeTo(null);
        propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
        
        
    }//GEN-LAST:event_PropertyMouseClicked

    private void PropertyImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropertyImagesMouseClicked

        PROPERTY_IMAGES_WINDOW propertyImagesForm = new PROPERTY_IMAGES_WINDOW();
        propertyImagesForm.setVisible(true);
        propertyImagesForm.pack();
        propertyImagesForm.setLocationRelativeTo(null);
        propertyImagesForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
        
        
    }//GEN-LAST:event_PropertyImagesMouseClicked

    private void SaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaleMouseClicked
        
        SALE_WINDOW saleForm = new SALE_WINDOW();
        saleForm.setVisible(true);
        saleForm.pack();
        saleForm.setLocationRelativeTo(null);
        saleForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
 
    }//GEN-LAST:event_SaleMouseClicked

    private void SaleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaleMouseEntered
        Sale.setBackground(Color.white);
        Sale.setForeground(new Color(102,102,102));
       
    }//GEN-LAST:event_SaleMouseEntered

    private void SaleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaleMouseExited
        Sale.setBackground(new Color(102,102,102));
        Sale.setForeground(Color.white);
    }//GEN-LAST:event_SaleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_APP_WINDOW().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Client;
    private javax.swing.JLabel Owner;
    private javax.swing.JLabel Property;
    private javax.swing.JLabel PropertyImages;
    private javax.swing.JLabel PropertyType;
    private javax.swing.JLabel Sale;
    private javax.swing.JLabel jLabel_APP_ICON;
    private javax.swing.JLabel jLabel_AppName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
