
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class SALE_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form SALE_WINDOW
     */
    public SALE_WINDOW() {
        initComponents();

        Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(255, 10, 0));
        jPanel_Title.setBorder(panel_title_border);

        Border button_border = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(255, 255, 255));
        Add_Sale.setBorder(button_border);
        Edit_Sale.setBorder(button_border);
        Remove_Sale.setBorder(button_border);

        fillJtableProperties();
        jTable_Properties.setRowHeight(40);
        jTable_Properties.setSelectionBackground(new Color(27, 150, 77));

        fillJtableClients();
        jTable_Clients.setRowHeight(40);
        jTable_Clients.setSelectionBackground(new Color(20,120,10));

        fillJtableSales();
        jTable_Sales.setRowHeight(40);
        jTable_Sales.setSelectionBackground(new Color(0,100,0));

    }

    public void fillJtableProperties() {
        P_PROPERTY property = new P_PROPERTY();

        ArrayList<P_PROPERTY> propertyList = property.propertiesList();

        String[] colNames = {"Id", "OwnerId", "Price"};
        Object[][] rows = new Object[propertyList.size()][3];

        for (int i = 0; i < propertyList.size(); i++) {
            rows[i][0] = propertyList.get(i).getId();
            rows[i][1] = propertyList.get(i).getOwnerId();
            rows[i][2] = propertyList.get(i).getPrice();
        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Properties.setModel(model);

    }

    public void fillJtableClients() {
        P_CLIENT client = new P_CLIENT();

        ArrayList<P_CLIENT> clientList = client.clientList();

        String[] colNames = {"ID", "First Name", "Last Name"};
        Object[][] rows = new Object[clientList.size()][3];

        for (int i = 0; i < clientList.size(); i++) {
            rows[i][0] = clientList.get(i).getId();
            rows[i][1] = clientList.get(i).getFirstName();
            rows[i][2] = clientList.get(i).getLastName();

        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Clients.setModel(model);

       

    }
    
    public void fillJtableSales() {
        P_SALE sale = new P_SALE();

        ArrayList<P_SALE> salesList = sale.salesList();

        String[] colNames = {"ID", "Property", "Client","Price","Date"};
        Object[][] rows = new Object[salesList.size()][5];

        for (int i = 0; i < salesList.size(); i++) {
            rows[i][0] = salesList.get(i).getId();
            rows[i][1] = salesList.get(i).getPropertyId();
            rows[i][2] = salesList.get(i).getClientId();
            rows[i][3] = salesList.get(i).getFinalPrice();
            rows[i][4] = salesList.get(i).getSellingDate();


        }

        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_Sales.setModel(model);

       

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Edit_Sale = new javax.swing.JButton();
        Remove_Sale = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFinalPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClientId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPropertyId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Properties = new javax.swing.JTable();
        Add_Sale = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Clients = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Sales = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        Refresh_Client = new javax.swing.JButton();
        Refresh_Property = new javax.swing.JButton();
        Refresh_Sales = new javax.swing.JButton();
        Add_Property = new javax.swing.JButton();
        Add_Client = new javax.swing.JButton();
        jDateChooser_SaleDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jPanel_Title.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sale");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(621, 621, 621))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("ID:");

        Edit_Sale.setBackground(new java.awt.Color(0, 102, 153));
        Edit_Sale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Edit_Sale.setForeground(new java.awt.Color(255, 255, 255));
        Edit_Sale.setText("Edit");
        Edit_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_SaleActionPerformed(evt);
            }
        });

        Remove_Sale.setBackground(new java.awt.Color(255, 51, 0));
        Remove_Sale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Remove_Sale.setForeground(new java.awt.Color(255, 255, 255));
        Remove_Sale.setText("Remove");
        Remove_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Remove_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_SaleActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Client ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Final Price:");

        txtFinalPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Date:");

        txtClientId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Property ID:");

        txtPropertyId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTable_Properties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Properties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PropertiesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Properties);

        Add_Sale.setBackground(new java.awt.Color(0, 102, 0));
        Add_Sale.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Add_Sale.setForeground(new java.awt.Color(255, 255, 255));
        Add_Sale.setText("Add");
        Add_Sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_SaleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Properties List");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Clients List");

        jTable_Clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ClientsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Clients);

        jTable_Sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SalesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_Sales);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Sales List");

        Refresh_Client.setBackground(new java.awt.Color(255, 204, 51));
        Refresh_Client.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Refresh_Client.setText("Refresh");
        Refresh_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_ClientActionPerformed(evt);
            }
        });

        Refresh_Property.setBackground(new java.awt.Color(255, 204, 51));
        Refresh_Property.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Refresh_Property.setText("Refresh");
        Refresh_Property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh_Property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_PropertyActionPerformed(evt);
            }
        });

        Refresh_Sales.setBackground(new java.awt.Color(255, 204, 51));
        Refresh_Sales.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Refresh_Sales.setText("Refresh");
        Refresh_Sales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh_Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_SalesActionPerformed(evt);
            }
        });

        Add_Property.setBackground(new java.awt.Color(0, 102, 0));
        Add_Property.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Add_Property.setForeground(new java.awt.Color(255, 255, 255));
        Add_Property.setText("Add New Property");
        Add_Property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_PropertyActionPerformed(evt);
            }
        });

        Add_Client.setBackground(new java.awt.Color(0, 102, 0));
        Add_Client.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Add_Client.setForeground(new java.awt.Color(255, 255, 255));
        Add_Client.setText("Add New Client");
        Add_Client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Add_Sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edit_Sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Remove_Sale, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtPropertyId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFinalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jDateChooser_SaleDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Refresh_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Refresh_Client, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_Property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh_Property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Refresh_Client)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Refresh_Sales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                        .addComponent(Add_Client)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Refresh_Property)
                                .addGap(18, 18, 18)
                                .addComponent(Add_Property))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtPropertyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFinalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jDateChooser_SaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addComponent(Add_Sale)
                                .addGap(18, 18, 18)
                                .addComponent(Edit_Sale)
                                .addGap(18, 18, 18)
                                .addComponent(Remove_Sale)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ClientActionPerformed
        CLIENT_WINDOW clientform = new CLIENT_WINDOW();
        clientform.setVisible(true);
        clientform.pack();
        clientform.setLocationRelativeTo(null);
        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_Add_ClientActionPerformed

    private void Add_PropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_PropertyActionPerformed

        PROPERTY_WINDOW propertyform = new PROPERTY_WINDOW();
        propertyform.setVisible(true);
        propertyform.pack();
        propertyform.setLocationRelativeTo(null);
        propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_Add_PropertyActionPerformed

    private void Refresh_SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_SalesActionPerformed

        fillJtableSales();

    }//GEN-LAST:event_Refresh_SalesActionPerformed

    private void Refresh_PropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_PropertyActionPerformed

        fillJtableProperties();

    }//GEN-LAST:event_Refresh_PropertyActionPerformed

    private void Refresh_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_ClientActionPerformed

        fillJtableClients();

    }//GEN-LAST:event_Refresh_ClientActionPerformed

    private void jTable_SalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SalesMouseClicked
        int selectedRowIndex = jTable_Sales.getSelectedRow();
        txtId.setText(jTable_Sales.getValueAt(selectedRowIndex, 0).toString());
        txtPropertyId.setText(jTable_Sales.getValueAt(selectedRowIndex, 1).toString());
        txtClientId.setText(jTable_Sales.getValueAt(selectedRowIndex, 2).toString());
        txtFinalPrice.setText(jTable_Sales.getValueAt(selectedRowIndex, 3).toString());

        Date saleDate;
        try {
            saleDate = new SimpleDateFormat("yyyy-MM-dd").parse(jTable_Sales.getValueAt(selectedRowIndex, 4).toString());
            jDateChooser_SaleDate.setDate(saleDate);

        } catch (ParseException ex) {
            Logger.getLogger(SALE_WINDOW.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable_SalesMouseClicked

    private void jTable_ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ClientsMouseClicked
        int selectedRowIndex = jTable_Clients.getSelectedRow();
        txtClientId.setText(jTable_Clients.getValueAt(selectedRowIndex, 0).toString());

    }//GEN-LAST:event_jTable_ClientsMouseClicked

    private void Add_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_SaleActionPerformed
        //int id = Integer.valueOf(txtId.getText());
        try{
            int propertyId = Integer.valueOf(txtPropertyId.getText());
            int clientId = Integer.valueOf(txtClientId.getText());
            String finalPrice = txtFinalPrice.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String sellingDate = dateFormat.format(jDateChooser_SaleDate.getDate());

            P_SALE sale = new P_SALE(0, propertyId, clientId, finalPrice, sellingDate);

            if(new P_SALE().addNewSale(sale)){
                JOptionPane.showMessageDialog(null, "A New Sale Has Been Created And Added.", "Add Sale", 1);

            } else {
                JOptionPane.showMessageDialog(null, "Sale Not Created.", "Add Sale", 2);

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select the Property Id,Client Id and Sale date.", "Add Sale Error", 2);

        }

    }//GEN-LAST:event_Add_SaleActionPerformed

    private void jTable_PropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PropertiesMouseClicked
        int selectedRowIndex = jTable_Properties.getSelectedRow();
        txtPropertyId.setText(jTable_Properties.getValueAt(selectedRowIndex, 0).toString());
        txtFinalPrice.setText(jTable_Properties.getValueAt(selectedRowIndex, 2).toString());
    }//GEN-LAST:event_jTable_PropertiesMouseClicked

    private void Remove_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_SaleActionPerformed

        try{
            int id = Integer.valueOf(txtId.getText());

            if(new P_SALE().deleteSale(id)){
                JOptionPane.showMessageDialog(null, "Sale Has Been Deleted.", "Delete Sale", 1);

            } else {
                JOptionPane.showMessageDialog(null, "Sale Not Deleted.", "Delete sale", 2);

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select the Sale Id.", "Delete sale Error", 2);

        }
    }//GEN-LAST:event_Remove_SaleActionPerformed

    private void Edit_SaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_SaleActionPerformed
        try{
            int id = Integer.valueOf(txtId.getText());
            int propertyId = Integer.valueOf(txtPropertyId.getText());
            int clientId = Integer.valueOf(txtClientId.getText());
            String finalPrice = txtFinalPrice.getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String sellingDate = dateFormat.format(jDateChooser_SaleDate.getDate());

            P_SALE sale = new P_SALE(id, propertyId, clientId, finalPrice, sellingDate);

            if(new P_SALE().editSale(sale)){
                JOptionPane.showMessageDialog(null, "Sale Data Has Been Updated.", "Edit Sale", 1);

            } else {
                JOptionPane.showMessageDialog(null, "Sale Data Not Updated.", "Edit Sale", 2);

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select the Property Id,Client Id and Sale date.", "Edit Sale Error", 2);

        }
    }//GEN-LAST:event_Edit_SaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SALE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SALE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SALE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SALE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SALE_WINDOW().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Client;
    private javax.swing.JButton Add_Property;
    private javax.swing.JButton Add_Sale;
    private javax.swing.JButton Edit_Sale;
    private javax.swing.JButton Refresh_Client;
    private javax.swing.JButton Refresh_Property;
    private javax.swing.JButton Refresh_Sales;
    private javax.swing.JButton Remove_Sale;
    private com.toedter.calendar.JDateChooser jDateChooser_SaleDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Clients;
    private javax.swing.JTable jTable_Properties;
    private javax.swing.JTable jTable_Sales;
    private javax.swing.JTextField txtClientId;
    private javax.swing.JTextField txtFinalPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPropertyId;
    // End of variables declaration//GEN-END:variables
}
